# Generated by Django 3.2.16 on 2022-12-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='label',
            new_name='name',
        ),
    ]
